#! /bin/sh
#
# chkconfig: 2345 90 10
# description:  cassandra-reaper daemon

. /lib/lsb/init-functions

# You will probably want to change only two following lines.
BASEDIR="/opt/cassandra-reaper"
USER="root"

PROG="cassandra-reaper"
CMD="${BASEDIR}/cassandra-reaper"
PIDFILE="${BASEDIR}/cassandra-reaper.pid"
RETVAL=0
 
start () {
    echo -n $"Starting ${PROG}"
    if ( [ -f ${PIDFILE} ] )
    then
        echo -n "${PROG} is already running."
        log_failure_msg ; echo
        RETVAL=1
        return
    fi
    touch ${PIDFILE} ; chown ${USER} ${PIDFILE}
    su ${USER} -c "cd ${BASEDIR}
      ${CMD} > ${BASEDIR}/cassandra-reaper.log 2>&1 &
      echo \$! > ${PIDFILE}"
    log_success_msg ; echo
}

stop () {
    echo -n $"Stopping ${PROG}"
    if ( [ ! -f ${PIDFILE} ] )
    then
        echo -n "${PROG} is not running."
        log_failure_msg ; echo
        RETVAL=1
        return
    fi
    killproc -p ${PIDFILE}
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ] ; then
        rm -f ${PIDFILE}
    fi
}

status () {
    if ( [ -f ${PIDFILE} ] )
    then
        echo -n "${PROG} is running."
	else
        echo -n "${PROG} is not running."
    fi
	echo
}

restart () {
    stop
    start
}


# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    RETVAL=2
    ;;
esac

exit $RETVAL
